[theme]
primaryColor = "#1a73e8"         # Streamlit blue (you can customize)
backgroundColor = "#ffffff"      # White background
secondaryBackgroundColor = "#f5f5f5"  # Light grey for widgets
textColor = "#000000"            # Black text
font = "sans serif"
